# Introduction to Python

## Chapter 3 - Python Functions

A function is a piece of reusable code that solves a particular task. Python ships with many built in functions and we have used ones like type() and print() already. You call a function rather than writing code yourself. For example, if you wanted to figure out who was the tallest person on your fam list, you could write code that goes over every element in the list and figures out which one is the greatest value, or you could use the Python function max().

In [1]:
fam = [1.73, 1.68, 1.71, 1.89]
max(fam)

1.89

Functions like round() can accept multiple arguments. Round takes the first argument provided between the parenthesis and rounds it to the decimal position defined in the second agrument, with the arguments separated by a comma (,).

In [2]:
round(1.68, 1)

1.7

Many functions have default arguments in case one is not specified. For the round() function, the second argument is optional and if a value for the decimal position is not specified, round() will assume 0 for the decimal position and round the value argument to the closest integer.

In [3]:
round(1.68)

2

In [4]:
round(1.2)

1

The documentation for all Python arguments can be reviewed within Python by placing the function name inside the help() function.

In [5]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



### Exercise 1

#### Familiar functions
Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: print() and type(). You've also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.<br>
Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following:<br>
<br>
result = type(3.0)<br>
<br>
The general recipe for calling functions and saving the result to a variable is thus:<br>
<br>
output = function_name(input)

__Instructions:__
* Use print() in combination with type() to print out the type of var1.
* Use len() to get the length of the list var1. Wrap it in a print() call to directly print it out.
* Use int() to convert var2 to an integer. Store the output as out2.

In [6]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


#### Multiple arguments
In the previous exercise, the square brackets around imag in the documentation showed us that the imag argument is optional. But Python also uses a different way to tell users about arguments being optional.<br>
<br>
Have a look at the documentation of sorted() by typing help(sorted) in the IPython Shell.<br>
<br>
You'll see that sorted() takes three arguments: iterable, key and reverse.<br>
<br>
key=None means that if you don't specify the key argument, it will be None. reverse=False means that if you don't specify the reverse argument, it will be False.<br>
<br>
In this exercise, you'll only have to specify iterable and reverse, not key. The first input you pass to sorted() will be matched to the iterable argument, but what about the second input? To tell Python you want to specify reverse without changing anything about key, you can use =:<br>
<br>
sorted(iterable, reverse = TrueorFalse)<br>
<br>
Two lists have been created for you on the right. Can you paste them together and sort them in descending order?
Note: For now, we can understand an iterable as being any collection of objects, e.g. a List.

__Instructions:__
* Use + to merge the contents of first and second into a new list: full.
* Call sorted() on full and specify the reverse argument to be True. Save the sorted list as full_sorted.
* Finish off by printing out full_sorted

In [7]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first+second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


### Methods
Python objects like str, float and list come with Methods or functions that belong to Python objects. <br>
* String objects have methods like capitalize() and replace() <br>
* Float objects have methods like bit_length() and conjugate()<br>
* List objects have methods like index() and count()

In [8]:
#List Methods
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

#If you want to find the index for an element in list, you can use the .index() list method and supply it with the element value
fam.index('mom')

4

In [9]:
#The .count() list method will return how often a value is found in a list
fam.count(1.71)

1

In [10]:
#String Methods
sister = 'liz'
sister

'liz'

In [11]:
#Use the .capitalize() string method if you want to capitalize the value in the variable sister
sister.capitalize()

'Liz'

In [12]:
#Use the .replace() string method if you want to replace some part of the value of the string
sister.replace('z', 'sa')

'lisa'

Everything in Python is an object and all object types have methods associated with them, depending on the object type. Not all object methods are available across every type of object. String objects have a .replace() method, but list objects don't.

In [13]:
sister.replace('sa', 'z')

'liz'

But the list object does not have a .replace()

In [16]:
fam.replace('mom', 'mommy')

AttributeError: 'list' object has no attribute 'replace'

But, both string objects and list objects have .index() methods

In [14]:
sister.index('i')

1

In [15]:
fam.index('mom')

4

Some Methods can actually change the object they are calling

In [16]:
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam.append('me')
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']

In [17]:
fam.append(1.60)
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.6]

### Exercise 2

#### String Methods
Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, you can always type help(str) in the IPython Shell.

A string place has already been created for you to experiment with.

__Instructions:__
* Use the upper() method on place and store the result in place_up. Use the syntax for calling methods that you learned in the previous video.
* Print out place and place_up. Did both change?
* Print out the number of o's on the variable place by calling count() on place and passing the letter 'o' as an input to the method. We're talking about the variable place, not the word "place"!

In [18]:
#String Methods
place = 'poolhouse'

#Use upper() on place: place_upper
place_up = place.upper()

#Print out place and place_up
print(place)
print(place_up)

#Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


#### List Methods

Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

* index(), to get the index of the first element of a list that matches its input and
* count(), to get the number of times an element appears in a list.

You'll be working on the list with the area of different parts of a house: areas.

__Instructions:__
* Use the index() method to get the index of the element in areas that is equal to 20.0. Print out this index.
* Call count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.

In [26]:
#Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#Print out the index of the element 20.0
print(areas.index(20.0))

#Print out how often 9.5 appears in the areas
print(areas.count(9.5))

2
1


#### List Methods (2)

Most list methods will change the list they're called on. Examples are:

* append(), that adds an element to the list it is called on,
* remove(), that removes the first element of a list that matches the input, and
* reverse(), that reverses the order of the elements in the list it is called on.
You'll be working on the list with the area of different parts of the house: areas.

__Instructions:__
* Use append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
* Print out areas
* Use the reverse() method to reverse the order of the elements in areas.
* Print out areas once more.

In [20]:
#Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

#Print areas
print(areas)

#Reverse the orders of the elements in areas
areas.reverse()

#Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


### Packages
Rather than packing every function into the entire Python base, there are packages that are a directory of Python scripts. Each script is a module that contains functions, methods and types that solve specific problems. There are 1000s of packages for Python. To use Python packages you will have to install them on your computer and then tell your Python script, through code, that you want to use the package.

To install packages you need to use pip, a package maintenance system for Python. http://pip.readthedocs.org/stable/installing to download get-pip.py. Then, from the terminal, you type:
> python3 get-pip.py

If you want to install the numpy package, from the terminal you type:
>pip3 install numpy

To then use the installed package in your script, you have import the package into your code. To import the entire numpy package, you can add import numpy to your code. In order to use any of the numpy functionality, you will have to tell Python that you want to use a numpy capability, like the numpy array() function. 



In [21]:
import numpy

array([1,2,3])

NameError: name 'array' is not defined

In [22]:
numpy.array([1,2,3])

array([1, 2, 3])

Rather than having to type out numpy every time you want to use a numpy capability, you can extend the import statement to import the package with a shorter name, np for numpy.

In [23]:
import numpy as np
np.array([1,2,4])

array([1, 2, 4])

There are cases where you only want a specific part of a package. Suppose you only want the array function from Numpy.

In [24]:
from numpy import array
array([1,3,5])

array([1, 3, 5])

### Exercise 3

#### Import package
As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

For a fancy clustering algorithm, you want to find the circumference, C, and area, A, of a circle. When the radius of the circle is r, you can calculate C and A as:

C=2πr<br>
A=πr2<br>
<br>
To use the constant pi, you'll need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

__Instructions:__
* Import the math package. Now you can access the constant pi with math.pi.
* Calculate the circumference of the circle and store it in C.
* Calculate the area of the circle and store it in A.

In [27]:
#Import the math package
import math

#Define radius
r = 0.43

#Calculate circumference
c = 2*math.pi*r**2

#Calculate area
a =math.pi*r**2

#Build printout
print('Circumference: ' + str(c))
print('Area: ' + str(a))

Circumference: 1.1617609632975054
Area: 0.5808804816487527


#### Selective import

General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

from math import pi
Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius r (in km) that is defined in the script.

__Instructions:__
* Perform a selective import from the math package where you only import the radians function.
* Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.
* Print out dist.

In [28]:
#Define radius
r = 192500

#Import radians function from math package
from math import radians

#Travel distance of Moon over 12 degrees. Store in dist
dist = r * radians(12)

print(dist)

40317.10572106901
